resources:
- repo: self

trigger:
- master

jobs:
- template: build-for-arch.yml
  parameters:
    arch: amd64
- template: build-for-arch.yml
  parameters:
    arch: i386
- template: build-for-arch.yml
  parameters:
    arch: arm64
- template: build-for-arch.yml
  parameters:
    arch: armhf
